version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017' 
    restart: always  
  server:
    build: ./server
    container_name: server_backend
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true